# .github/workflows/main.yml

name: GKE Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Check everything is correct
      run: |
        echo docker buildx build . \
          --platform linux/amd64 \
          -t ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/gke-python-app:$GITHUB_SHA \
          --push

    - name: Build Docker Image for linux/amd64
      run: |
        docker buildx build . \
          --platform linux/amd64 \
          -t ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/gke-python-app:$GITHUB_SHA \
          --push

    - name: Deploy to GKE using Helm
      run: |
        helm upgrade --install gke-python-release ./helm-chart \
          --set image.repository=${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/gke-python-app \
          --set image.tag=$GITHUB_SHA \
          --set service.type=LoadBalancer

    - name: Get Service External IP
      run: |
        echo "Waiting for LoadBalancer to get an external IP..."
        sleep 60  # Wait for a minute to ensure the IP is assigned
        export SERVICE_IP=$(kubectl get svc --namespace default gke-python-release --template="{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
        echo "The application is available at: http://$SERVICE_IP:8080"
